#!/bin/bash

if [[ $# -lt 1 ]]
then
  echo "No tweet specified."
  exit
fi

touch tweets.txt
for tweet do
thedate=`date +%a\ %b\ %d\ %Y\ %X\ GMT%z\ \(%Z\)`»
echo $thedate
(tmpfile=`mktemp` && { echo "${thedate}
${tweet}" | cat - tweets.txt > $tmpfile && mv $tmpfile tweets.txt; } );
done
if [[ $# -gt 1 ]]
then
  git commit tweets.txt -m "Autogenerated commit of $# tweets."
else
  git commit tweets.txt -m "Autogenerated commit of tweet."
fi
git push
echo "cd /home/flaviusb && pwd && . ./.bashrc && cd code/my-tweets && git pull && byeloblog.ik build.ik -m $#" | ssh -t -t flaviusb@flaviusb.net
