#!/bin/bash

touch tweets.txt
thedate=`date +%a\ %b\ %d\ %Y\ %X\ GMT%z\ \(%Z\)`»
echo $thedate
(tmpfile=`mktemp` && { echo "${thedate}
$1" | cat - tweets.txt > $tmpfile && mv $tmpfile tweets.txt; } )
git commit tweets.txt -m "Autogenerated commit of tweet."
git push
echo "cd ~ && pwd && . ./.bashrc && cd code/tweets && git pull && coffee post.coffee \"$1\" && byeloblog.ik" | ssh -t -t flaviusb@flaviusb.net
