#!/bin/bash

touch tweets.txt
thedate=`date +%a\ %b\ %d\ %Y\ %X\ GMT%z\ \(%Z\)`»
echo $thedate
(tmpfile=`mktemp` && { echo "${thedate}
$1" | cat - tweets.txt > $tmpfile && mv $tmpfile tweets.txt; } )
git commit tweets.txt -m "Autogenerated commit of tweet."
git push
echo "cd /home/flaviusb && pwd && . ./.bashrc && cd code/my-tweets && git pull && byeloblog.ik build.ik -m" | ssh -t -t flaviusb@flaviusb.net
